services:
  mysql-profiler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mysql-profiler
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./data:/data
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1 # To get logs in real time
    labels:
      - "dockpeek.link=http://192.168.50.32:38110"
      - "dockpeek.tags=mysql-profiler,profiler"
